// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VinhKhanh.Infrastructure.Data;

#nullable disable

namespace VinhKhanh.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260325225736_AddPoiQrCodeAndIndexes")]
    partial class AddPoiQrCodeAndIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VinhKhanh.Infrastructure.Data.AppHistoryLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<int?>("PoiId")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TourId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EventType");

                    b.ToTable("AppHistoryLogs", (string)null);
                });

            modelBuilder.Entity("VinhKhanh.Infrastructure.Data.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("OwnedPoiId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("VinhKhanh.Infrastructure.Data.MovementLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<float>("AccuracyMeters")
                        .HasColumnType("real");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("SessionId");

                    b.ToTable("MovementLogs", (string)null);
                });

            modelBuilder.Entity("VinhKhanh.Infrastructure.Data.Poi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioViUrl")
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("ContentVersion")
                        .HasColumnType("integer");

                    b.Property<int>("CooldownSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<double>("MapX")
                        .HasColumnType("double precision");

                    b.Property<double>("MapY")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("OwnerInfo")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("QrCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("TriggerRadiusMeters")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("ContentVersion");

                    b.HasIndex("QrCode")
                        .IsUnique()
                        .HasFilter("\"QrCode\" IS NOT NULL");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("Pois", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            ContentVersion = 1,
                            CooldownSeconds = 60,
                            CreatedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Com tam dac trung Sai Gon 30 nam.",
                            IsActive = true,
                            Latitude = 10.7531,
                            Longitude = 106.678,
                            MapX = 15.0,
                            MapY = 40.0,
                            Name = "Quan Com Tam Ba Ghien",
                            Priority = 9,
                            QrCode = "VK-POI-001",
                            TriggerRadiusMeters = 15.0,
                            UpdatedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            ContentVersion = 1,
                            CooldownSeconds = 60,
                            CreatedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Banh canh cua tuoi boc day, 40 nam.",
                            IsActive = true,
                            Latitude = 10.753299999999999,
                            Longitude = 106.6781,
                            MapX = 30.0,
                            MapY = 40.0,
                            Name = "Banh Canh Cua Ba Suong",
                            Priority = 8,
                            QrCode = "VK-POI-002",
                            TriggerRadiusMeters = 15.0,
                            UpdatedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Category = 3,
                            ContentVersion = 1,
                            CooldownSeconds = 120,
                            CreatedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Khu vuc tap trung hang che.",
                            IsActive = true,
                            Latitude = 10.754,
                            Longitude = 106.6785,
                            MapX = 75.0,
                            MapY = 40.0,
                            Name = "Khu Che Cuoi Pho",
                            Priority = 5,
                            QrCode = "VK-POI-003",
                            TriggerRadiusMeters = 20.0,
                            UpdatedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("VinhKhanh.Infrastructure.Data.PoiTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("PoiId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PoiId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("PoiTranslations", (string)null);
                });

            modelBuilder.Entity("VinhKhanh.Infrastructure.Data.PoiVisitLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("ListenDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("PoiId")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.HasIndex("VisitedAt");

                    b.ToTable("PoiVisitLogs", (string)null);
                });

            modelBuilder.Entity("VinhKhanh.Infrastructure.Data.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Tours", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Com tam -> Banh canh -> Che",
                            EstimatedMinutes = 60,
                            IsActive = true,
                            Name = "Tour Am Thuc 1 Gio Vinh Khanh",
                            UpdatedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("VinhKhanh.Infrastructure.Data.TourStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("PoiId")
                        .HasColumnType("integer");

                    b.Property<int>("StayMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("StopOrder")
                        .HasColumnType("integer");

                    b.Property<int>("TourId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PoiId");

                    b.HasIndex("TourId", "StopOrder")
                        .IsUnique();

                    b.ToTable("TourStops", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PoiId = 1,
                            StayMinutes = 20,
                            StopOrder = 1,
                            TourId = 1
                        },
                        new
                        {
                            Id = 2,
                            PoiId = 2,
                            StayMinutes = 20,
                            StopOrder = 2,
                            TourId = 1
                        },
                        new
                        {
                            Id = 3,
                            PoiId = 3,
                            StayMinutes = 20,
                            StopOrder = 3,
                            TourId = 1
                        });
                });

            modelBuilder.Entity("VinhKhanh.Infrastructure.Data.TourTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("TourId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TourId");

                    b.ToTable("TourTranslations", (string)null);
                });

            modelBuilder.Entity("VinhKhanh.Infrastructure.Data.PoiTranslation", b =>
                {
                    b.HasOne("VinhKhanh.Infrastructure.Data.Poi", "Poi")
                        .WithMany("Translations")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("VinhKhanh.Infrastructure.Data.PoiVisitLog", b =>
                {
                    b.HasOne("VinhKhanh.Infrastructure.Data.Poi", "Poi")
                        .WithMany("VisitLogs")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("VinhKhanh.Infrastructure.Data.TourStop", b =>
                {
                    b.HasOne("VinhKhanh.Infrastructure.Data.Poi", "Poi")
                        .WithMany("TourStops")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VinhKhanh.Infrastructure.Data.Tour", "Tour")
                        .WithMany("Stops")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("VinhKhanh.Infrastructure.Data.TourTranslation", b =>
                {
                    b.HasOne("VinhKhanh.Infrastructure.Data.Tour", "Tour")
                        .WithMany("Translations")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("VinhKhanh.Infrastructure.Data.Poi", b =>
                {
                    b.Navigation("TourStops");

                    b.Navigation("Translations");

                    b.Navigation("VisitLogs");
                });

            modelBuilder.Entity("VinhKhanh.Infrastructure.Data.Tour", b =>
                {
                    b.Navigation("Stops");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
