//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VinhKhanh.App.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VinhKhanh.App.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string ChatSendButton {
            get {
                return ResourceManager.GetString("ChatSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off GPS.
        /// </summary>
        public static string GpsButtonOff {
            get {
                return ResourceManager.GetString("GpsButtonOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On GPS.
        /// </summary>
        public static string GpsButtonOn {
            get {
                return ResourceManager.GetString("GpsButtonOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking stopped..
        /// </summary>
        public static string GpsStatusStopped {
            get {
                return ResourceManager.GetString("GpsStatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking GPS in background....
        /// </summary>
        public static string GpsStatusTracking {
            get {
                return ResourceManager.GetString("GpsStatusTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for location....
        /// </summary>
        public static string GpsStatusWait {
            get {
                return ResourceManager.GetString("GpsStatusWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguagePickerTitle {
            get {
                return ResourceManager.GetString("LanguagePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string LanguageSelectionContinue {
            get {
                return ResourceManager.GetString("LanguageSelectionContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your preferred language.
        /// </summary>
        public static string LanguageSelectionDesc {
            get {
                return ResourceManager.GetString("LanguageSelectionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string LanguageSelectionTitle {
            get {
                return ResourceManager.GetString("LanguageSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading map..
        /// </summary>
        public static string MapLoadingError {
            get {
                return ResourceManager.GetString("MapLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinh Khanh Map.
        /// </summary>
        public static string MapTitle {
            get {
                return ResourceManager.GetString("MapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio error: {0}.
        /// </summary>
        public static string NarrationStatusError {
            get {
                return ResourceManager.GetString("NarrationStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished ({0}s): {1}.
        /// </summary>
        public static string NarrationStatusFinished {
            get {
                return ResourceManager.GetString("NarrationStatusFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No POI to play..
        /// </summary>
        public static string NarrationStatusNoPoi {
            get {
                return ResourceManager.GetString("NarrationStatusNoPoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing: {0}.
        /// </summary>
        public static string NarrationStatusPlaying {
            get {
                return ResourceManager.GetString("NarrationStatusPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest: {0}.
        /// </summary>
        public static string NearestLabelFormat {
            get {
                return ResourceManager.GetString("NearestLabelFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback: {0}.
        /// </summary>
        public static string PlaybackPoiLabel {
            get {
                return ResourceManager.GetString("PlaybackPoiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEAREST LOCATION.
        /// </summary>
        public static string PoiDetailNearestLabel {
            get {
                return ResourceManager.GetString("PoiDetailNearestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Audio.
        /// </summary>
        public static string PoiDetailReadAudio {
            get {
                return ResourceManager.GetString("PoiDetailReadAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visited: {0}.
        /// </summary>
        public static string QrFoundSatus {
            get {
                return ResourceManager.GetString("QrFoundSatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No POI found for this QR code..
        /// </summary>
        public static string QrNotFoundStatus {
            get {
                return ResourceManager.GetString("QrNotFoundStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter POI code manually.
        /// </summary>
        public static string QrPlaceholder {
            get {
                return ResourceManager.GetString("QrPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point camera at QR code (vk-poi-123 or URL with /poi/123).
        /// </summary>
        public static string QrScanHint {
            get {
                return ResourceManager.GetString("QrScanHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string QrSubmitButton {
            get {
                return ResourceManager.GetString("QrSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android emulator: 10.0.2.2 instead of localhost. Real device: PC&apos;s LAN IP..
        /// </summary>
        public static string SettingsApiHint {
            get {
                return ResourceManager.GetString("SettingsApiHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API URL (with or without trailing /).
        /// </summary>
        public static string SettingsApiUrlLabel {
            get {
                return ResourceManager.GetString("SettingsApiUrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geofence radius multiplier (1 = default).
        /// </summary>
        public static string SettingsGeofenceRadiusLabel {
            get {
                return ResourceManager.GetString("SettingsGeofenceRadiusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On: blue-dot automatically loops through POIs..
        /// </summary>
        public static string SettingsMockGpsDesc {
            get {
                return ResourceManager.GetString("SettingsMockGpsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable GPS Simulation (.NET Mock).
        /// </summary>
        public static string SettingsMockGpsLabel {
            get {
                return ResourceManager.GetString("SettingsMockGpsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SettingsSaveButton {
            get {
                return ResourceManager.GetString("SettingsSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully..
        /// </summary>
        public static string SettingsSavedSuccess {
            get {
                return ResourceManager.GetString("SettingsSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding nearest location....
        /// </summary>
        public static string StatusNearestPoiDefault {
            get {
                return ResourceManager.GetString("StatusNearestPoiDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string SyncButton {
            get {
                return ResourceManager.GetString("SyncButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error - reading cache..
        /// </summary>
        public static string SyncStatusNetworkError {
            get {
                return ResourceManager.GetString("SyncStatusNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data. Check API..
        /// </summary>
        public static string SyncStatusNoData {
            get {
                return ResourceManager.GetString("SyncStatusNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline: {0} POIs in cache..
        /// </summary>
        public static string SyncStatusOffline {
            get {
                return ResourceManager.GetString("SyncStatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synced {0} POIs..
        /// </summary>
        public static string SyncStatusSuccess {
            get {
                return ResourceManager.GetString("SyncStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing POIs....
        /// </summary>
        public static string SyncStatusSyncing {
            get {
                return ResourceManager.GetString("SyncStatusSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatbot.
        /// </summary>
        public static string TabChat {
            get {
                return ResourceManager.GetString("TabChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string TabMap {
            get {
                return ResourceManager.GetString("TabMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR.
        /// </summary>
        public static string TabScan {
            get {
                return ResourceManager.GetString("TabScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string TabSettings {
            get {
                return ResourceManager.GetString("TabSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours.
        /// </summary>
        public static string TabTours {
            get {
                return ResourceManager.GetString("TabTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try syncing again or check API connection..
        /// </summary>
        public static string ToursEmptySubtitle {
            get {
                return ResourceManager.GetString("ToursEmptySubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tours found..
        /// </summary>
        public static string ToursEmptyTitle {
            get {
                return ResourceManager.GetString("ToursEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string ToursHeader {
            get {
                return ResourceManager.GetString("ToursHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration: {0} mins.
        /// </summary>
        public static string ToursItemMinutes {
            get {
                return ResourceManager.GetString("ToursItemMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops: {0}.
        /// </summary>
        public static string ToursItemStopsCount {
            get {
                return ResourceManager.GetString("ToursItemStopsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food tour recommendations.
        /// </summary>
        public static string ToursSubtitle {
            get {
                return ResourceManager.GetString("ToursSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading tours..
        /// </summary>
        public static string ToursSyncError {
            get {
                return ResourceManager.GetString("ToursSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours Details.
        /// </summary>
        public static string ToursTitle
        {
            get
            {
                return ResourceManager.GetString("ToursTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        public static string TabPois {
            get {
                return ResourceManager.GetString("TabPois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search restaurants....
        /// </summary>
        public static string PoiSearchPlaceholder {
            get {
                return ResourceManager.GetString("PoiSearchPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No restaurants found.
        /// </summary>
        public static string PoiEmptyList {
            get {
                return ResourceManager.GetString("PoiEmptyList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reload data.
        /// </summary>
        public static string PoiReloadButton {
            get {
                return ResourceManager.GetString("PoiReloadButton", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Play Narration.
        /// </summary>
        public static string PlayNarration {
            get {
                return ResourceManager.GetString("PlayNarration", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop Narration.
        /// </summary>
        public static string StopNarration {
            get {
                return ResourceManager.GetString("StopNarration", resourceCulture);
            }
        }
    }
}
